# Generated by Django 5.2.1 on 2025-06-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_razorpay_order_id_booking_razorpay_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_signature',
        ),
    ]
